### ISSUE TITLE
Merge pb

### ISSUE THREAD

**Issue by merlindorin** [eoko/kes#1]
@MaximeMaillet je crois que tu as eu un soucis de merge...

https://github.com/eoko/kes/blob/c8c71120f7d685e2e6b83cd363b1730600cd3c50/src/Plugins/SkuPlugin/SkuPlugin.php#L26

**Comment by MaximeMaillet** [comment]
Issue fixée.

Merge approximatif car je n'avais aucune idée quelle était la version à jour. De plus, les sources ont été supprimées.
